# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - osx
  - linux
  - windows

warnings_are_errors: false

compiler:
  - gcc